<?php
/**
 * @var \Bold\CheckoutFlowPaypal\Block\System\Config\Form\Field\Toggle $block
 */
?>

<?= $block->getButtonHtml() ?>

<script type="text/x-magento-init">
    {
        "#paypal_flow_toggle": {
            "Bold_CheckoutFlowPaypal/js/paypal-toggle": {
                "url": "<?= $block->getToggleUrl(); ?>",
                "enabled": "<?= $block->isEnabled(); ?>",
                "title": "<?= /* @escapeNotVerified */ __('Enabling the PayPal Checkout Flow will deactivate all active Bold-hosted flows') ?>",
                "content": "<?= /* @escapeNotVerified */ __('The PayPal Checkout Flow replaces any active Bold-hosted Checkout flows. You may deactivate the Paypal Checkout Flow at any time to reactive your Bold-hosted flows.') ?>",
                "alert": "<?= /* @escapeNotVerified */ __('Something went wrong') ?>"
            }
        }
    }
</script>
